<?php
require_once dirname(__DIR__,2).'/lib/bootstrap.php';require_method('POST');require_csrf();$actor=require_permission('USUARIOS_GESTIONAR');$in=json_input();
$id=(int)($in['usuario_id']??0);$username=strtolower(trim((string)($in['username']??'')));$name=trim((string)($in['nombre']??''));$ap=trim((string)($in['apellido_paterno']??''));$am=trim((string)($in['apellido_materno']??''));$email=strtolower(trim((string)($in['email']??'')));$phone=trim((string)($in['telefono']??''));$position=trim((string)($in['puesto']??''));$status=in_array(($in['estatus']??'ACTIVO'),['ACTIVO','INACTIVO','BLOQUEADO'],true)?$in['estatus']:'ACTIVO';$password=(string)($in['password']??'');$departmentId=($in['departamento_id']??'')!==''?(int)$in['departamento_id']:null;$roleId=(int)($in['rol_id']??0);$bossId=($in['jefe_usuario_id']??'')!==''?(int)$in['jefe_usuario_id']:null;
if($username===''||$name===''||$roleId<=0)json_response(['ok'=>false,'error'=>'Usuario, nombre y rol son obligatorios'],400);if($id<=0&&strlen($password)<8)json_response(['ok'=>false,'error'=>'La contraseña inicial debe tener al menos 8 caracteres'],400);
$db=conectar();if(!$db)json_response(['ok'=>false,'error'=>'Sin conexión a base de datos'],503);if(!user_is_global($actor)){if($departmentId===null||!in_array($departmentId,visible_department_ids($db,$actor),true)){$db->close();json_response(['ok'=>false,'error'=>'No puedes administrar usuarios fuera de tu departamento'],403);}}$db->begin_transaction();
try{$before=null;if($id>0){$st=$db->prepare("SELECT usuario_id,username,nombre,email,estatus FROM usuario WHERE usuario_id=?");$st->bind_param('i',$id);$st->execute();$before=$st->get_result()->fetch_assoc();$st->close();if($password!==''){$hash=password_hash($password,PASSWORD_DEFAULT);$st=$db->prepare("UPDATE usuario SET username=?,nombre=?,apellido_paterno=?,apellido_materno=?,email=NULLIF(?,''),telefono=?,puesto=?,estatus=?,password_hash=?,requiere_cambio_password=1,bloqueado_hasta=NULL,intentos_fallidos=0 WHERE usuario_id=?");$st->bind_param('sssssssssi',$username,$name,$ap,$am,$email,$phone,$position,$status,$hash,$id);}else{$st=$db->prepare("UPDATE usuario SET username=?,nombre=?,apellido_paterno=?,apellido_materno=?,email=NULLIF(?,''),telefono=?,puesto=?,estatus=? WHERE usuario_id=?");$st->bind_param('ssssssssi',$username,$name,$ap,$am,$email,$phone,$position,$status,$id);}$st->execute();$st->close();}
else{$hash=password_hash($password,PASSWORD_DEFAULT);$uuid=bin2hex(random_bytes(16));$uuid=substr($uuid,0,8).'-'.substr($uuid,8,4).'-4'.substr($uuid,13,3).'-a'.substr($uuid,17,3).'-'.substr($uuid,20,12);$actorId=(int)$actor['user_id'];$st=$db->prepare("INSERT INTO usuario(uuid,username,nombre,apellido_paterno,apellido_materno,email,telefono,puesto,password_hash,estatus,requiere_cambio_password,created_by_usuario_id) VALUES(?,?,?,?,?,NULLIF(?,''),?,?,?,?,1,?)");$st->bind_param('ssssssssssi',$uuid,$username,$name,$ap,$am,$email,$phone,$position,$hash,$status,$actorId);$st->execute();$id=(int)$st->insert_id;$st->close();}
$st=$db->prepare("SELECT alcance FROM rol WHERE rol_id=? AND estatus='ACTIVO'");$st->bind_param('i',$roleId);$st->execute();$role=$st->get_result()->fetch_assoc();$st->close();if(!$role)throw new RuntimeException('Rol no válido');if($role['alcance']!=='GLOBAL'&&(!$departmentId||$departmentId<=0))throw new RuntimeException('Este rol requiere un departamento');if($bossId!==null&&$bossId===$id)throw new RuntimeException('Un usuario no puede ser su propio jefe');
$st=$db->prepare("UPDATE usuario_departamento SET estatus='INACTIVO',es_principal=0 WHERE usuario_id=? AND estatus='ACTIVO'");$st->bind_param('i',$id);$st->execute();$st->close();$actorId=(int)$actor['user_id'];$dep=$role['alcance']==='GLOBAL'?null:$departmentId;$st=$db->prepare("INSERT INTO usuario_departamento(usuario_id,departamento_id,rol_id,jefe_usuario_id,es_principal,estatus,created_by_usuario_id) VALUES(?,?,?,?,1,'ACTIVO',?)");$st->bind_param('iiiii',$id,$dep,$roleId,$bossId,$actorId);$st->execute();$st->close();
audit_log($db,$actorId,$before?'USUARIO_EDITAR':'USUARIO_CREAR','USUARIO',$id,$username,$before,$in);$db->commit();$db->close();json_response(['ok'=>true,'data'=>['usuario_id'=>$id]]);
}catch(Throwable $e){$db->rollback();$db->close();json_response(['ok'=>false,'error'=>'No se pudo guardar el usuario: '.$e->getMessage()],409);}
