<?php
$user=$_SESSION['user'];$perms=$user['permissions']??[];function nav_ok(array $p,string $code):bool{return in_array($code,$p,true);} 
$viewTitles=['dashboard'=>'Resumen','departamentos'=>'Departamentos','usuarios'=>'Usuarios y jerarquía','roles'=>'Roles y permisos','presupuestos'=>'Presupuestos','subitems'=>'Sub-items','solicitudes'=>'Solicitudes','movimientos'=>'Movimientos','nuevo-movimiento'=>'Registrar movimiento','aclaraciones'=>'Aclaraciones y seguimiento','bitacora'=>'Bitácora'];$pageTitle=$viewTitles[$view]??'Presupuesto';
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#5f7f6a"><title><?=htmlspecialchars($pageTitle)?> | Presupuesto Ixtlahuacán</title><link rel="stylesheet" href="css/styles.css"><link rel="stylesheet" href="css/presupuesto.css"></head><body>
<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="sidebar-head"><img src="img/ixtla/main_logo.png" alt="Ixtlahuacán"><button class="icon-btn mobile-only" id="closeSidebar">✕</button></div><div class="product-badge"><span>Presupuesto</span><small>Gestión Municipal</small></div><nav class="nav-list">
<a class="<?=$view==='dashboard'?'active':''?>" href="?view=dashboard"><span>⌂</span>Resumen</a>
<?php if(nav_ok($perms,'DEPARTAMENTOS_GESTIONAR')):?><a class="<?=$view==='departamentos'?'active':''?>" href="?view=departamentos"><span>🏛</span>Departamentos</a><?php endif;?>
<?php if(nav_ok($perms,'USUARIOS_GESTIONAR')):?><a class="<?=$view==='usuarios'?'active':''?>" href="?view=usuarios"><span>👥</span>Usuarios</a><?php endif;?>
<?php if(nav_ok($perms,'ROLES_GESTIONAR')):?><a class="<?=$view==='roles'?'active':''?>" href="?view=roles"><span>🛡</span>Roles y permisos</a><?php endif;?>
<?php if(nav_ok($perms,'PRESUPUESTO_VER')):?><a class="<?=$view==='presupuestos'?'active':''?>" href="?view=presupuestos"><span>💰</span>Presupuestos</a><?php endif;?>
<?php if(nav_ok($perms,'SUBITEMS_GESTIONAR')):?><a class="<?=$view==='subitems'?'active':''?>" href="?view=subitems"><span>🏷</span>Sub-items</a><?php endif;?>
<?php if(nav_ok($perms,'SOLICITUD_CREAR')||nav_ok($perms,'SOLICITUD_APROBAR')):?><a class="<?=$view==='solicitudes'?'active':''?>" href="?view=solicitudes"><span>📝</span>Solicitudes</a><?php endif;?>
<?php if(nav_ok($perms,'MOVIMIENTO_VER')):?><a class="<?=$view==='movimientos'?'active':''?>" href="?view=movimientos"><span>⇄</span>Movimientos</a><?php endif;?>
<?php if(nav_ok($perms,'ACLARACION_CREAR')||nav_ok($perms,'ACLARACION_GESTIONAR')):?><a class="<?=$view==='aclaraciones'?'active':''?>" href="?view=aclaraciones"><span>💬</span>Aclaraciones</a><?php endif;?>
<?php if(nav_ok($perms,'BITACORA_VER')):?><a class="<?=$view==='bitacora'?'active':''?>" href="?view=bitacora"><span>🧾</span>Bitácora</a><?php endif;?>
</nav><div class="sidebar-foot"><div class="user-card"><div class="avatar"><?=htmlspecialchars(strtoupper(substr($user['name']??'U',0,1)))?></div><div><strong><?=htmlspecialchars($user['name']??'Usuario')?></strong><small><?=htmlspecialchars(implode(' · ',user_role_codes($user)))?></small></div></div><button class="btn btn-ghost btn-sm" id="logoutBtn">Cerrar sesión</button></div></aside>
<div class="main-area"><header class="topbar"><button class="icon-btn menu-btn" id="openSidebar">☰</button><div><span class="eyebrow">PRESUPUESTO IXTLAHUACÁN</span><h1><?=htmlspecialchars($pageTitle)?></h1></div><div class="top-actions"><span class="scope-chip"><?=user_is_global($user)?'Vista global':'Vista de mi alcance'?></span><?php if(nav_ok($perms,'MOVIMIENTO_SALIDA_CREAR')||nav_ok($perms,'MOVIMIENTO_ENTRADA_CREAR')):?><a class="btn btn-primary" href="?view=nuevo-movimiento">+ Movimiento</a><?php endif;?></div></header><main class="content"><?php include __DIR__.'/'.$view.'.php';?></main><footer class="app-footer"><span>Gobierno Municipal de Ixtlahuacán · Presupuesto</span><span>Los movimientos y cambios quedan auditados.</span></footer></div></div>
<nav class="mobile-bottom-nav" aria-label="Navegación rápida móvil">
<a class="<?=$view==='dashboard'?'active':''?>" href="?view=dashboard"><span>⌂</span><small>Inicio</small></a>
<?php if(nav_ok($perms,'MOVIMIENTO_VER')):?><a class="<?=$view==='movimientos'?'active':''?>" href="?view=movimientos"><span>⇄</span><small>Movimientos</small></a><?php endif;?>
<?php if(nav_ok($perms,'SOLICITUD_CREAR')||nav_ok($perms,'SOLICITUD_APROBAR')):?><a class="<?=$view==='solicitudes'?'active':''?>" href="?view=solicitudes"><span>📝</span><small>Solicitudes</small></a><?php endif;?>
<?php if(nav_ok($perms,'ACLARACION_CREAR')||nav_ok($perms,'ACLARACION_GESTIONAR')):?><a class="<?=$view==='aclaraciones'?'active':''?>" href="?view=aclaraciones"><span>💬</span><small>Seguimiento</small></a><?php endif;?>
</nav>
<div id="toastRoot" class="toast-root"></div><div class="modal-backdrop hidden" id="globalBackdrop"></div>
<script>window.PROIXTLA_USER=<?=json_encode($user,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;window.PROIXTLA_CSRF=<?=json_encode($_SESSION['csrf']??'')?>;</script><script src="js/app.js"></script><script src="js/<?=$view==='nuevo-movimiento'?'movimientos':$view?>.js"></script></body></html>
