<?php
require_once dirname(__DIR__,2).'/lib/bootstrap.php';require_method('POST');require_csrf();$user=require_login();
$isMultipart=str_contains(strtolower((string)($_SERVER['CONTENT_TYPE']??'')),'multipart/form-data');$in=$isMultipart?$_POST:json_input();$type=strtoupper(trim((string)($in['tipo']??'SALIDA')));if(!in_array($type,['ENTRADA','SALIDA'],true))json_response(['ok'=>false,'error'=>'Tipo de movimiento inválido'],400);if($type==='SALIDA'&&!user_has_permission($user,'MOVIMIENTO_SALIDA_CREAR'))json_response(['ok'=>false,'error'=>'Solo Tesorería, Presidencia o Administración pueden registrar salidas reales'],403);if($type==='ENTRADA'&&!user_has_permission($user,'MOVIMIENTO_ENTRADA_CREAR'))json_response(['ok'=>false,'error'=>'No tienes permiso para registrar entradas'],403);
$db=conectar();if(!$db)json_response(['ok'=>false,'error'=>'Sin conexión a base de datos'],503);$requestId=(int)($in['solicitud_id']??0);$request=null;
if($requestId>0){$st=$db->prepare("SELECT * FROM presupuesto_solicitud WHERE solicitud_id=? LIMIT 1");$st->bind_param('i',$requestId);$st->execute();$request=$st->get_result()->fetch_assoc();$st->close();if(!$request){$db->close();json_response(['ok'=>false,'error'=>'Solicitud no encontrada'],404);}if($request['estatus']!=='AUTORIZADA'){$db->close();json_response(['ok'=>false,'error'=>'La solicitud debe estar AUTORIZADA antes de registrarse como salida'],409);}}
$dep=$request?(int)$request['departamento_id']:(int)($in['departamento_id']??0);$sub=$request?($request['subitem_id']!==null?(int)$request['subitem_id']:null):(($in['subitem_id']??'')!==''?(int)$in['subitem_id']:null);$year=$request?(int)$request['ejercicio']:(int)($in['ejercicio']??date('Y'));$date=trim((string)($in['fecha']??date('Y-m-d')));$amount=$request?(float)$request['monto_solicitado']:money_value($in['monto']??0);$concept=$request?(string)$request['concepto']:trim((string)($in['concepto']??''));$requester=$request?(int)$request['solicitado_por_usuario_id']:(($in['solicitado_por_usuario_id']??'')!==''?(int)$in['solicitado_por_usuario_id']:(int)$user['user_id']);$benefUser=$request?($request['otorgado_a_usuario_id']!==null?(int)$request['otorgado_a_usuario_id']:null):(($in['otorgado_a_usuario_id']??'')!==''?(int)$in['otorgado_a_usuario_id']:null);$benefName=$request?(string)($request['beneficiario_nombre']??''):trim((string)($in['beneficiario_nombre']??''));$area=$request?(string)($request['area_solicitante']??''):trim((string)($in['area_solicitante']??''));$method=strtoupper(trim((string)($in['metodo_pago']??'')));$reference=trim((string)($in['referencia']??''));if($dep<=0||$year<2020||$year>2100||$amount<=0||$concept===''){$db->close();json_response(['ok'=>false,'error'=>'Departamento, monto y concepto son obligatorios'],400);}if(!in_array($method,['EFECTIVO','TRANSFERENCIA','CHEQUE','TARJETA','OTRO'],true))$method=null;if($type==='SALIDA'){$balance=department_balance($db,$dep,$year);if($amount>$balance['disponible']){$db->close();json_response(['ok'=>false,'error'=>'La salida excede el presupuesto disponible del departamento'],409);}}
if(!user_is_global($user)&&!in_array($dep,visible_department_ids($db,$user),true)){$db->close();json_response(['ok'=>false,'error'=>'No puedes registrar movimientos para ese departamento'],403);}$requestDbId=$requestId>0?$requestId:null;$folio=next_folio($db,'MOVIMIENTO',$year);$uid=(int)$user['user_id'];$fileSaved=null;$db->begin_transaction();
try{$st=$db->prepare("INSERT INTO presupuesto_movimiento(folio,ejercicio,departamento_id,subitem_id,solicitud_id,tipo,fecha,monto,concepto,solicitado_por_usuario_id,otorgado_a_usuario_id,beneficiario_nombre,area_solicitante,metodo_pago,referencia,estatus,registrado_por_usuario_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'REGISTRADO',?)");$st->bind_param('siiiissdsiissssi',$folio,$year,$dep,$sub,$requestDbId,$type,$date,$amount,$concept,$requester,$benefUser,$benefName,$area,$method,$reference,$uid);$st->execute();$id=(int)$st->insert_id;$st->close();if($requestId>0){$st=$db->prepare("UPDATE presupuesto_solicitud SET estatus='PAGADA',movimiento_id=?,resuelto_por_usuario_id=?,resuelto_at=NOW() WHERE solicitud_id=?");$st->bind_param('iii',$id,$uid,$requestId);$st->execute();$st->close();}
if(isset($_FILES['evidencia'])){$fileSaved=save_evidence_file($_FILES['evidencia'],$folio);if($fileSaved){$st=$db->prepare("INSERT INTO presupuesto_movimiento_archivo(movimiento_id,nombre_original,nombre_guardado,ruta_relativa,mime_type,size_bytes,uploaded_by_usuario_id) VALUES(?,?,?,?,?,?,?)");$st->bind_param('issssii',$id,$fileSaved['nombre_original'],$fileSaved['nombre_guardado'],$fileSaved['ruta_relativa'],$fileSaved['mime_type'],$fileSaved['size_bytes'],$uid);$st->execute();$st->close();}}
audit_log($db,$uid,'MOVIMIENTO_'.$type,'MOVIMIENTO',$id,$folio,null,['folio'=>$folio,'tipo'=>$type,'departamento_id'=>$dep,'monto'=>$amount,'concepto'=>$concept,'solicitud_id'=>$requestId?:null,'otorgado_a_usuario_id'=>$benefUser,'beneficiario_nombre'=>$benefName]);$db->commit();$balance=department_balance($db,$dep,$year);$db->close();json_response(['ok'=>true,'data'=>['movimiento_id'=>$id,'folio'=>$folio,'balance'=>$balance]]);}catch(Throwable $e){$db->rollback();if($fileSaved&&isset($fileSaved['ruta_relativa']))@unlink(project_root().'/'.$fileSaved['ruta_relativa']);$db->close();json_response(['ok'=>false,'error'=>'No se pudo registrar el movimiento: '.$e->getMessage()],500);}
