<?php
require_once dirname(__DIR__,2).'/lib/bootstrap.php';require_method('GET');$user=require_login();$year=max(2020,min(2100,(int)($_GET['year']??date('Y'))));$db=conectar();if(!$db)json_response(['ok'=>false,'error'=>'Sin conexión a base de datos'],503);$ids=visible_department_ids($db,$user);if(!$ids){$db->close();json_response(['ok'=>true,'data'=>['totals'=>['asignado'=>0,'entradas'=>0,'salidas'=>0,'disponible'=>0,'ejercido_pct'=>0],'departments'=>[],'monthly'=>array_fill(1,12,['entrada'=>0,'salida'=>0]),'pending_requests'=>0,'open_clarifications'=>0]]);}$idList=implode(',',array_map('intval',$ids));
$sql="SELECT d.departamento_id,d.codigo,d.nombre,d.color_hex,COALESCE(pd.presupuesto_asignado,0) asignado,
COALESCE(SUM(CASE WHEN pm.tipo='ENTRADA' AND pm.estatus='REGISTRADO' THEN pm.monto ELSE 0 END),0) entradas,
COALESCE(SUM(CASE WHEN pm.tipo='SALIDA' AND pm.estatus='REGISTRADO' THEN pm.monto ELSE 0 END),0) salidas
FROM departamento d LEFT JOIN presupuesto_departamento pd ON pd.departamento_id=d.departamento_id AND pd.ejercicio=$year AND pd.estatus='ACTIVO'
LEFT JOIN presupuesto_movimiento pm ON pm.departamento_id=d.departamento_id AND pm.ejercicio=$year
WHERE d.departamento_id IN ($idList) AND d.estatus='ACTIVO'
GROUP BY d.departamento_id,d.codigo,d.nombre,d.color_hex,pd.presupuesto_asignado ORDER BY d.nombre";
$rs=$db->query($sql);$deps=[];$tot=['asignado'=>0.0,'entradas'=>0.0,'salidas'=>0.0,'disponible'=>0.0];while($r=$rs->fetch_assoc()){$a=(float)$r['asignado'];$e=(float)$r['entradas'];$s=(float)$r['salidas'];$dis=$a+$e-$s;$deps[]=['departamento_id'=>(int)$r['departamento_id'],'codigo'=>$r['codigo'],'nombre'=>$r['nombre'],'color_hex'=>$r['color_hex'],'asignado'=>$a,'entradas'=>$e,'salidas'=>$s,'disponible'=>$dis,'ejercido_pct'=>$a>0?round(($s/$a)*100,1):0];$tot['asignado']+=$a;$tot['entradas']+=$e;$tot['salidas']+=$s;$tot['disponible']+=$dis;}
$tot['ejercido_pct']=$tot['asignado']>0?round(($tot['salidas']/$tot['asignado'])*100,1):0.0;
$monthly=[];for($m=1;$m<=12;$m++)$monthly[$m]=['entrada'=>0.0,'salida'=>0.0];$rs=$db->query("SELECT pm.*,MONTH(pm.fecha) mes FROM presupuesto_movimiento pm WHERE pm.ejercicio=$year AND pm.estatus='REGISTRADO' AND pm.departamento_id IN ($idList) ORDER BY pm.fecha");if($rs)while($r=$rs->fetch_assoc()){if(!movement_is_visible($db,$user,$r))continue;$m=(int)$r['mes'];$k=$r['tipo']==='ENTRADA'?'entrada':'salida';$monthly[$m][$k]+=(float)$r['monto'];}
$pending=0;$rs=$db->query("SELECT * FROM presupuesto_solicitud WHERE ejercicio=$year AND estatus IN ('PENDIENTE','AUTORIZADA') AND departamento_id IN ($idList)");if($rs)while($r=$rs->fetch_assoc())if(request_is_visible($db,$user,$r)||user_has_permission($user,'SOLICITUD_APROBAR'))$pending++;
$open=0;$sql="SELECT a.aclaracion_id,pm.* FROM movimiento_aclaracion a JOIN presupuesto_movimiento pm ON pm.movimiento_id=a.movimiento_id WHERE a.estatus IN ('ABIERTA','EN_REVISION') AND pm.departamento_id IN ($idList)";$rs=$db->query($sql);if($rs)while($r=$rs->fetch_assoc())if(movement_is_visible($db,$user,$r))$open++;
$db->close();json_response(['ok'=>true,'data'=>['totals'=>$tot,'departments'=>$deps,'monthly'=>$monthly,'pending_requests'=>$pending,'open_clarifications'=>$open]]);
